// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/model/v1/health.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthStatus int32

const (
	HealthStatus_HEALTH_UNKNOWN HealthStatus = 0
	HealthStatus_HEALTH_ONLINE  HealthStatus = 1
	HealthStatus_HEALTH_OFFLINE HealthStatus = 2
	HealthStatus_HEALTH_ERROR   HealthStatus = 3
)

var HealthStatus_name = map[int32]string{
	0: "HEALTH_UNKNOWN",
	1: "HEALTH_ONLINE",
	2: "HEALTH_OFFLINE",
	3: "HEALTH_ERROR",
}

var HealthStatus_value = map[string]int32{
	"HEALTH_UNKNOWN": 0,
	"HEALTH_ONLINE":  1,
	"HEALTH_OFFLINE": 2,
	"HEALTH_ERROR":   3,
}

func (x HealthStatus) String() string {
	return proto.EnumName(HealthStatus_name, int32(x))
}

func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a9e68dd7d671de82, []int{0}
}

type Health struct {
	Status               HealthStatus `protobuf:"varint,1,opt,name=status,proto3,enum=v1.model.HealthStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Health) Reset()         { *m = Health{} }
func (m *Health) String() string { return proto.CompactTextString(m) }
func (*Health) ProtoMessage()    {}
func (*Health) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e68dd7d671de82, []int{0}
}

func (m *Health) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Health.Unmarshal(m, b)
}
func (m *Health) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Health.Marshal(b, m, deterministic)
}
func (m *Health) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Health.Merge(m, src)
}
func (m *Health) XXX_Size() int {
	return xxx_messageInfo_Health.Size(m)
}
func (m *Health) XXX_DiscardUnknown() {
	xxx_messageInfo_Health.DiscardUnknown(m)
}

var xxx_messageInfo_Health proto.InternalMessageInfo

func (m *Health) GetStatus() HealthStatus {
	if m != nil {
		return m.Status
	}
	return HealthStatus_HEALTH_UNKNOWN
}

type Battery struct {
	Percentage           float64  `protobuf:"fixed64,1,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Voltage              float64  `protobuf:"fixed64,2,opt,name=voltage,proto3" json:"voltage,omitempty"`
	Current              float64  `protobuf:"fixed64,3,opt,name=current,proto3" json:"current,omitempty"`
	Charge               float64  `protobuf:"fixed64,4,opt,name=charge,proto3" json:"charge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Battery) Reset()         { *m = Battery{} }
func (m *Battery) String() string { return proto.CompactTextString(m) }
func (*Battery) ProtoMessage()    {}
func (*Battery) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e68dd7d671de82, []int{1}
}

func (m *Battery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Battery.Unmarshal(m, b)
}
func (m *Battery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Battery.Marshal(b, m, deterministic)
}
func (m *Battery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Battery.Merge(m, src)
}
func (m *Battery) XXX_Size() int {
	return xxx_messageInfo_Battery.Size(m)
}
func (m *Battery) XXX_DiscardUnknown() {
	xxx_messageInfo_Battery.DiscardUnknown(m)
}

var xxx_messageInfo_Battery proto.InternalMessageInfo

func (m *Battery) GetPercentage() float64 {
	if m != nil {
		return m.Percentage
	}
	return 0
}

func (m *Battery) GetVoltage() float64 {
	if m != nil {
		return m.Voltage
	}
	return 0
}

func (m *Battery) GetCurrent() float64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *Battery) GetCharge() float64 {
	if m != nil {
		return m.Charge
	}
	return 0
}

func init() {
	proto.RegisterEnum("v1.model.HealthStatus", HealthStatus_name, HealthStatus_value)
	proto.RegisterType((*Health)(nil), "v1.model.Health")
	proto.RegisterType((*Battery)(nil), "v1.model.Battery")
}

func init() { proto.RegisterFile("protos/model/v1/health.proto", fileDescriptor_a9e68dd7d671de82) }

var fileDescriptor_a9e68dd7d671de82 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4b, 0xf3, 0x40,
	0x10, 0xc5, 0xbf, 0xb4, 0x1f, 0xa9, 0x0c, 0xb5, 0xc4, 0x3d, 0x94, 0x1c, 0x44, 0xa4, 0x27, 0x11,
	0xdc, 0xa5, 0x8a, 0xe8, 0xd5, 0x62, 0x4a, 0xc4, 0x92, 0x40, 0xac, 0x08, 0x7a, 0x90, 0x4d, 0xba,
	0x24, 0x85, 0xa4, 0x5b, 0x36, 0x93, 0xa8, 0xff, 0xbd, 0x38, 0xd9, 0x42, 0x8e, 0xef, 0xf7, 0x7b,
	0x03, 0xc3, 0x83, 0xd3, 0xbd, 0xd1, 0xa8, 0x6b, 0x51, 0xe9, 0x8d, 0x2a, 0x45, 0x3b, 0x17, 0x85,
	0x92, 0x25, 0x16, 0x9c, 0x30, 0x3b, 0x6a, 0xe7, 0x9c, 0xcc, 0xec, 0x1e, 0xdc, 0x90, 0x0c, 0xe3,
	0xe0, 0xd6, 0x28, 0xb1, 0xa9, 0x7d, 0xe7, 0xdc, 0xb9, 0x98, 0x5c, 0x4f, 0xf9, 0xa1, 0xc4, 0xbb,
	0xc6, 0x0b, 0xd9, 0xc4, 0xb6, 0x66, 0x0d, 0x8c, 0x16, 0x12, 0x51, 0x99, 0x1f, 0x76, 0x06, 0xb0,
	0x57, 0x26, 0x53, 0x3b, 0x94, 0xb9, 0xa2, 0x73, 0x27, 0xe9, 0x11, 0xe6, 0xc3, 0xa8, 0xd5, 0x25,
	0xc9, 0x01, 0xc9, 0x43, 0xfc, 0x33, 0x59, 0x63, 0x8c, 0xda, 0xa1, 0x3f, 0xec, 0x8c, 0x8d, 0x6c,
	0x0a, 0x6e, 0x56, 0x48, 0x93, 0x2b, 0xff, 0x3f, 0x09, 0x9b, 0x2e, 0x3f, 0x60, 0xdc, 0x7f, 0x87,
	0x31, 0x98, 0x84, 0xc1, 0xc3, 0x6a, 0x1d, 0x7e, 0xbe, 0x46, 0xcf, 0x51, 0xfc, 0x16, 0x79, 0xff,
	0xd8, 0x09, 0x1c, 0x5b, 0x16, 0x47, 0xab, 0xa7, 0x28, 0xf0, 0x9c, 0x5e, 0x2d, 0x5e, 0x2e, 0x89,
	0x0d, 0x98, 0x07, 0x63, 0xcb, 0x82, 0x24, 0x89, 0x13, 0x6f, 0xb8, 0xb8, 0x7b, 0xbf, 0xcd, 0xb7,
	0x58, 0x34, 0x29, 0xcf, 0x74, 0x25, 0xd6, 0x4a, 0x56, 0x8f, 0x1a, 0xbf, 0xb4, 0x29, 0x37, 0xc2,
	0xe8, 0x54, 0xe3, 0xf6, 0xfb, 0x8a, 0x06, 0x14, 0x76, 0xdd, 0x76, 0xde, 0x0d, 0x9c, 0xba, 0x04,
	0x6e, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x10, 0x82, 0x0f, 0x77, 0x01, 0x00, 0x00,
}
