// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: protos/fleet_manager/v1/fleet_manager.proto

package fleet_manager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetManager_CommandStream_FullMethodName        = "/v1.fleet_manager.FleetManager/CommandStream"
	FleetManager_HerdServices_FullMethodName         = "/v1.fleet_manager.FleetManager/HerdServices"
	FleetManager_RobotTelemetry_FullMethodName       = "/v1.fleet_manager.FleetManager/RobotTelemetry"
	FleetManager_HerdTelemetry_FullMethodName        = "/v1.fleet_manager.FleetManager/HerdTelemetry"
	FleetManager_NavigationTelemetry_FullMethodName  = "/v1.fleet_manager.FleetManager/NavigationTelemetry"
	FleetManager_DockerStatsTelemetry_FullMethodName = "/v1.fleet_manager.FleetManager/DockerStatsTelemetry"
)

// FleetManagerClient is the client API for FleetManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FleetManagerClient interface {
	CommandStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommandSteamRequest, CommandSteamRespose], error)
	HerdServices(ctx context.Context, in *HerdServiceRequest, opts ...grpc.CallOption) (*HerdServiceResponse, error)
	RobotTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RobotTelemetryData, RobotTelemetryResponse], error)
	HerdTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HerdTelemetryReqest, HerdTelemetryResponse], error)
	NavigationTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NavTelemetryRequest, NavTelemetryResponse], error)
	DockerStatsTelemetry(ctx context.Context, in *DockerTelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DockerTelemetryResponse], error)
}

type fleetManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetManagerClient(cc grpc.ClientConnInterface) FleetManagerClient {
	return &fleetManagerClient{cc}
}

func (c *fleetManagerClient) CommandStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CommandSteamRequest, CommandSteamRespose], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetManager_ServiceDesc.Streams[0], FleetManager_CommandStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CommandSteamRequest, CommandSteamRespose]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetManager_CommandStreamClient = grpc.BidiStreamingClient[CommandSteamRequest, CommandSteamRespose]

func (c *fleetManagerClient) HerdServices(ctx context.Context, in *HerdServiceRequest, opts ...grpc.CallOption) (*HerdServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HerdServiceResponse)
	err := c.cc.Invoke(ctx, FleetManager_HerdServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetManagerClient) RobotTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RobotTelemetryData, RobotTelemetryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetManager_ServiceDesc.Streams[1], FleetManager_RobotTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RobotTelemetryData, RobotTelemetryResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetManager_RobotTelemetryClient = grpc.BidiStreamingClient[RobotTelemetryData, RobotTelemetryResponse]

func (c *fleetManagerClient) HerdTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HerdTelemetryReqest, HerdTelemetryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetManager_ServiceDesc.Streams[2], FleetManager_HerdTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HerdTelemetryReqest, HerdTelemetryResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetManager_HerdTelemetryClient = grpc.BidiStreamingClient[HerdTelemetryReqest, HerdTelemetryResponse]

func (c *fleetManagerClient) NavigationTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NavTelemetryRequest, NavTelemetryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetManager_ServiceDesc.Streams[3], FleetManager_NavigationTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NavTelemetryRequest, NavTelemetryResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetManager_NavigationTelemetryClient = grpc.BidiStreamingClient[NavTelemetryRequest, NavTelemetryResponse]

func (c *fleetManagerClient) DockerStatsTelemetry(ctx context.Context, in *DockerTelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DockerTelemetryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetManager_ServiceDesc.Streams[4], FleetManager_DockerStatsTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DockerTelemetryRequest, DockerTelemetryResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetManager_DockerStatsTelemetryClient = grpc.ServerStreamingClient[DockerTelemetryResponse]

// FleetManagerServer is the server API for FleetManager service.
// All implementations must embed UnimplementedFleetManagerServer
// for forward compatibility.
type FleetManagerServer interface {
	CommandStream(grpc.BidiStreamingServer[CommandSteamRequest, CommandSteamRespose]) error
	HerdServices(context.Context, *HerdServiceRequest) (*HerdServiceResponse, error)
	RobotTelemetry(grpc.BidiStreamingServer[RobotTelemetryData, RobotTelemetryResponse]) error
	HerdTelemetry(grpc.BidiStreamingServer[HerdTelemetryReqest, HerdTelemetryResponse]) error
	NavigationTelemetry(grpc.BidiStreamingServer[NavTelemetryRequest, NavTelemetryResponse]) error
	DockerStatsTelemetry(*DockerTelemetryRequest, grpc.ServerStreamingServer[DockerTelemetryResponse]) error
	mustEmbedUnimplementedFleetManagerServer()
}

// UnimplementedFleetManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetManagerServer struct{}

func (UnimplementedFleetManagerServer) CommandStream(grpc.BidiStreamingServer[CommandSteamRequest, CommandSteamRespose]) error {
	return status.Errorf(codes.Unimplemented, "method CommandStream not implemented")
}
func (UnimplementedFleetManagerServer) HerdServices(context.Context, *HerdServiceRequest) (*HerdServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HerdServices not implemented")
}
func (UnimplementedFleetManagerServer) RobotTelemetry(grpc.BidiStreamingServer[RobotTelemetryData, RobotTelemetryResponse]) error {
	return status.Errorf(codes.Unimplemented, "method RobotTelemetry not implemented")
}
func (UnimplementedFleetManagerServer) HerdTelemetry(grpc.BidiStreamingServer[HerdTelemetryReqest, HerdTelemetryResponse]) error {
	return status.Errorf(codes.Unimplemented, "method HerdTelemetry not implemented")
}
func (UnimplementedFleetManagerServer) NavigationTelemetry(grpc.BidiStreamingServer[NavTelemetryRequest, NavTelemetryResponse]) error {
	return status.Errorf(codes.Unimplemented, "method NavigationTelemetry not implemented")
}
func (UnimplementedFleetManagerServer) DockerStatsTelemetry(*DockerTelemetryRequest, grpc.ServerStreamingServer[DockerTelemetryResponse]) error {
	return status.Errorf(codes.Unimplemented, "method DockerStatsTelemetry not implemented")
}
func (UnimplementedFleetManagerServer) mustEmbedUnimplementedFleetManagerServer() {}
func (UnimplementedFleetManagerServer) testEmbeddedByValue()                      {}

// UnsafeFleetManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetManagerServer will
// result in compilation errors.
type UnsafeFleetManagerServer interface {
	mustEmbedUnimplementedFleetManagerServer()
}

func RegisterFleetManagerServer(s grpc.ServiceRegistrar, srv FleetManagerServer) {
	// If the following call pancis, it indicates UnimplementedFleetManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetManager_ServiceDesc, srv)
}

func _FleetManager_CommandStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FleetManagerServer).CommandStream(&grpc.GenericServerStream[CommandSteamRequest, CommandSteamRespose]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetManager_CommandStreamServer = grpc.BidiStreamingServer[CommandSteamRequest, CommandSteamRespose]

func _FleetManager_HerdServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HerdServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetManagerServer).HerdServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetManager_HerdServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetManagerServer).HerdServices(ctx, req.(*HerdServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetManager_RobotTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FleetManagerServer).RobotTelemetry(&grpc.GenericServerStream[RobotTelemetryData, RobotTelemetryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetManager_RobotTelemetryServer = grpc.BidiStreamingServer[RobotTelemetryData, RobotTelemetryResponse]

func _FleetManager_HerdTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FleetManagerServer).HerdTelemetry(&grpc.GenericServerStream[HerdTelemetryReqest, HerdTelemetryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetManager_HerdTelemetryServer = grpc.BidiStreamingServer[HerdTelemetryReqest, HerdTelemetryResponse]

func _FleetManager_NavigationTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FleetManagerServer).NavigationTelemetry(&grpc.GenericServerStream[NavTelemetryRequest, NavTelemetryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetManager_NavigationTelemetryServer = grpc.BidiStreamingServer[NavTelemetryRequest, NavTelemetryResponse]

func _FleetManager_DockerStatsTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DockerTelemetryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FleetManagerServer).DockerStatsTelemetry(m, &grpc.GenericServerStream[DockerTelemetryRequest, DockerTelemetryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetManager_DockerStatsTelemetryServer = grpc.ServerStreamingServer[DockerTelemetryResponse]

// FleetManager_ServiceDesc is the grpc.ServiceDesc for FleetManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.fleet_manager.FleetManager",
	HandlerType: (*FleetManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HerdServices",
			Handler:    _FleetManager_HerdServices_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CommandStream",
			Handler:       _FleetManager_CommandStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RobotTelemetry",
			Handler:       _FleetManager_RobotTelemetry_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "HerdTelemetry",
			Handler:       _FleetManager_HerdTelemetry_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "NavigationTelemetry",
			Handler:       _FleetManager_NavigationTelemetry_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DockerStatsTelemetry",
			Handler:       _FleetManager_DockerStatsTelemetry_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/fleet_manager/v1/fleet_manager.proto",
}
