// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: protos/model/v1/actions.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Compressed    bool                   `protobuf:"varint,3,opt,name=compressed,proto3" json:"compressed,omitempty"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	ScrubberTime  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=scrubber_time,json=scrubberTime,proto3" json:"scrubber_time,omitempty"`
	ParentId      string                 `protobuf:"bytes,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	RetryCount    int64                  `protobuf:"varint,7,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	SeqNum        int64                  `protobuf:"varint,8,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_protos_model_v1_actions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_v1_actions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_protos_model_v1_actions_proto_rawDescGZIP(), []int{0}
}

func (x *ActionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ActionRequest) GetCompressed() bool {
	if x != nil {
		return x.Compressed
	}
	return false
}

func (x *ActionRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ActionRequest) GetScrubberTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScrubberTime
	}
	return nil
}

func (x *ActionRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ActionRequest) GetRetryCount() int64 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *ActionRequest) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

type ActionResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status    bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	IsResult  bool                   `protobuf:"varint,3,opt,name=isResult,proto3" json:"isResult,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*ActionResponse_Data
	//	*ActionResponse_Raw
	//	*ActionResponse_Error
	Result        isActionResponse_Result `protobuf_oneof:"result"`
	ParentId      string                  `protobuf:"bytes,7,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	RetryCount    int64                   `protobuf:"varint,8,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	SeqNum        int64                   `protobuf:"varint,9,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_protos_model_v1_actions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_v1_actions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_protos_model_v1_actions_proto_rawDescGZIP(), []int{1}
}

func (x *ActionResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ActionResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ActionResponse) GetIsResult() bool {
	if x != nil {
		return x.IsResult
	}
	return false
}

func (x *ActionResponse) GetResult() isActionResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ActionResponse) GetData() string {
	if x != nil {
		if x, ok := x.Result.(*ActionResponse_Data); ok {
			return x.Data
		}
	}
	return ""
}

func (x *ActionResponse) GetRaw() []byte {
	if x != nil {
		if x, ok := x.Result.(*ActionResponse_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

func (x *ActionResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*ActionResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *ActionResponse) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ActionResponse) GetRetryCount() int64 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *ActionResponse) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

type isActionResponse_Result interface {
	isActionResponse_Result()
}

type ActionResponse_Data struct {
	Data string `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

type ActionResponse_Raw struct {
	Raw []byte `protobuf:"bytes,5,opt,name=raw,proto3,oneof"`
}

type ActionResponse_Error struct {
	Error string `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

func (*ActionResponse_Data) isActionResponse_Result() {}

func (*ActionResponse_Raw) isActionResponse_Result() {}

func (*ActionResponse_Error) isActionResponse_Result() {}

var File_protos_model_v1_actions_proto protoreflect.FileDescriptor

const file_protos_model_v1_actions_proto_rawDesc = "" +
	"\n" +
	"\x1dprotos/model/v1/actions.proto\x12\bv1.model\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x02\n" +
	"\rActionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1e\n" +
	"\n" +
	"compressed\x18\x03 \x01(\bR\n" +
	"compressed\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\x12?\n" +
	"\rscrubber_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fscrubberTime\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\tR\bparentId\x12\x1f\n" +
	"\vretry_count\x18\a \x01(\x03R\n" +
	"retryCount\x12\x17\n" +
	"\aseq_num\x18\b \x01(\x03R\x06seqNum\"\x86\x02\n" +
	"\x0eActionResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\x12\x1a\n" +
	"\bisResult\x18\x03 \x01(\bR\bisResult\x12\x14\n" +
	"\x04data\x18\x04 \x01(\tH\x00R\x04data\x12\x12\n" +
	"\x03raw\x18\x05 \x01(\fH\x00R\x03raw\x12\x16\n" +
	"\x05error\x18\x06 \x01(\tH\x00R\x05error\x12\x1b\n" +
	"\tparent_id\x18\a \x01(\tR\bparentId\x12\x1f\n" +
	"\vretry_count\x18\b \x01(\x03R\n" +
	"retryCount\x12\x17\n" +
	"\aseq_num\x18\t \x01(\x03R\x06seqNumB\b\n" +
	"\x06resultB9Z7github.com/GOAT-Robotics/gtstudio-proto/protos/v1/modelb\x06proto3"

var (
	file_protos_model_v1_actions_proto_rawDescOnce sync.Once
	file_protos_model_v1_actions_proto_rawDescData []byte
)

func file_protos_model_v1_actions_proto_rawDescGZIP() []byte {
	file_protos_model_v1_actions_proto_rawDescOnce.Do(func() {
		file_protos_model_v1_actions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_model_v1_actions_proto_rawDesc), len(file_protos_model_v1_actions_proto_rawDesc)))
	})
	return file_protos_model_v1_actions_proto_rawDescData
}

var file_protos_model_v1_actions_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_model_v1_actions_proto_goTypes = []any{
	(*ActionRequest)(nil),         // 0: v1.model.ActionRequest
	(*ActionResponse)(nil),        // 1: v1.model.ActionResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_protos_model_v1_actions_proto_depIdxs = []int32{
	2, // 0: v1.model.ActionRequest.scrubber_time:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_model_v1_actions_proto_init() }
func file_protos_model_v1_actions_proto_init() {
	if File_protos_model_v1_actions_proto != nil {
		return
	}
	file_protos_model_v1_actions_proto_msgTypes[1].OneofWrappers = []any{
		(*ActionResponse_Data)(nil),
		(*ActionResponse_Raw)(nil),
		(*ActionResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_model_v1_actions_proto_rawDesc), len(file_protos_model_v1_actions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_model_v1_actions_proto_goTypes,
		DependencyIndexes: file_protos_model_v1_actions_proto_depIdxs,
		MessageInfos:      file_protos_model_v1_actions_proto_msgTypes,
	}.Build()
	File_protos_model_v1_actions_proto = out.File
	file_protos_model_v1_actions_proto_goTypes = nil
	file_protos_model_v1_actions_proto_depIdxs = nil
}
