// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: protos/model/v1/datapoint.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Datapoint struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Stream    string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix epoch time in milliseconds
	Tags      map[string]string      `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Data:
	//
	//	*Datapoint_Text
	//	*Datapoint_Numeric
	//	*Datapoint_NumericSet
	//	*Datapoint_Bitset
	//	*Datapoint_File
	//	*Datapoint_Image
	//	*Datapoint_PointCloud
	//	*Datapoint_Location
	//	*Datapoint_Localization
	//	*Datapoint_Health
	//	*Datapoint_Json
	//	*Datapoint_Battery
	//	*Datapoint_Video
	//	*Datapoint_TransformTree
	//	*Datapoint_Raw
	Data          isDatapoint_Data `protobuf_oneof:"data"`
	Alarms        []*Alarm         `protobuf:"bytes,20,rep,name=alarms,proto3" json:"alarms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Datapoint) Reset() {
	*x = Datapoint{}
	mi := &file_protos_model_v1_datapoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Datapoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Datapoint) ProtoMessage() {}

func (x *Datapoint) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_v1_datapoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Datapoint.ProtoReflect.Descriptor instead.
func (*Datapoint) Descriptor() ([]byte, []int) {
	return file_protos_model_v1_datapoint_proto_rawDescGZIP(), []int{0}
}

func (x *Datapoint) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *Datapoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Datapoint) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Datapoint) GetData() isDatapoint_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Datapoint) GetText() *Text {
	if x != nil {
		if x, ok := x.Data.(*Datapoint_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *Datapoint) GetNumeric() *Numeric {
	if x != nil {
		if x, ok := x.Data.(*Datapoint_Numeric); ok {
			return x.Numeric
		}
	}
	return nil
}

func (x *Datapoint) GetNumericSet() *NumericSet {
	if x != nil {
		if x, ok := x.Data.(*Datapoint_NumericSet); ok {
			return x.NumericSet
		}
	}
	return nil
}

func (x *Datapoint) GetBitset() *Bitset {
	if x != nil {
		if x, ok := x.Data.(*Datapoint_Bitset); ok {
			return x.Bitset
		}
	}
	return nil
}

func (x *Datapoint) GetFile() *File {
	if x != nil {
		if x, ok := x.Data.(*Datapoint_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *Datapoint) GetImage() *Image {
	if x != nil {
		if x, ok := x.Data.(*Datapoint_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *Datapoint) GetPointCloud() *PointCloud {
	if x != nil {
		if x, ok := x.Data.(*Datapoint_PointCloud); ok {
			return x.PointCloud
		}
	}
	return nil
}

func (x *Datapoint) GetLocation() *Location {
	if x != nil {
		if x, ok := x.Data.(*Datapoint_Location); ok {
			return x.Location
		}
	}
	return nil
}

func (x *Datapoint) GetLocalization() *Localization {
	if x != nil {
		if x, ok := x.Data.(*Datapoint_Localization); ok {
			return x.Localization
		}
	}
	return nil
}

func (x *Datapoint) GetHealth() *Health {
	if x != nil {
		if x, ok := x.Data.(*Datapoint_Health); ok {
			return x.Health
		}
	}
	return nil
}

func (x *Datapoint) GetJson() *Json {
	if x != nil {
		if x, ok := x.Data.(*Datapoint_Json); ok {
			return x.Json
		}
	}
	return nil
}

func (x *Datapoint) GetBattery() *Battery {
	if x != nil {
		if x, ok := x.Data.(*Datapoint_Battery); ok {
			return x.Battery
		}
	}
	return nil
}

func (x *Datapoint) GetVideo() *Video {
	if x != nil {
		if x, ok := x.Data.(*Datapoint_Video); ok {
			return x.Video
		}
	}
	return nil
}

func (x *Datapoint) GetTransformTree() *TransformTree {
	if x != nil {
		if x, ok := x.Data.(*Datapoint_TransformTree); ok {
			return x.TransformTree
		}
	}
	return nil
}

func (x *Datapoint) GetRaw() []byte {
	if x != nil {
		if x, ok := x.Data.(*Datapoint_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

func (x *Datapoint) GetAlarms() []*Alarm {
	if x != nil {
		return x.Alarms
	}
	return nil
}

type isDatapoint_Data interface {
	isDatapoint_Data()
}

type Datapoint_Text struct {
	Text *Text `protobuf:"bytes,4,opt,name=text,proto3,oneof"`
}

type Datapoint_Numeric struct {
	Numeric *Numeric `protobuf:"bytes,5,opt,name=numeric,proto3,oneof"`
}

type Datapoint_NumericSet struct {
	NumericSet *NumericSet `protobuf:"bytes,17,opt,name=numeric_set,json=numericSet,proto3,oneof"`
}

type Datapoint_Bitset struct {
	Bitset *Bitset `protobuf:"bytes,7,opt,name=bitset,proto3,oneof"`
}

type Datapoint_File struct {
	File *File `protobuf:"bytes,8,opt,name=file,proto3,oneof"`
}

type Datapoint_Image struct {
	Image *Image `protobuf:"bytes,9,opt,name=image,proto3,oneof"`
}

type Datapoint_PointCloud struct {
	PointCloud *PointCloud `protobuf:"bytes,10,opt,name=point_cloud,json=pointCloud,proto3,oneof"`
}

type Datapoint_Location struct {
	Location *Location `protobuf:"bytes,11,opt,name=location,proto3,oneof"`
}

type Datapoint_Localization struct {
	Localization *Localization `protobuf:"bytes,12,opt,name=localization,proto3,oneof"`
}

type Datapoint_Health struct {
	Health *Health `protobuf:"bytes,13,opt,name=health,proto3,oneof"`
}

type Datapoint_Json struct {
	Json *Json `protobuf:"bytes,14,opt,name=json,proto3,oneof"`
}

type Datapoint_Battery struct {
	Battery *Battery `protobuf:"bytes,15,opt,name=battery,proto3,oneof"`
}

type Datapoint_Video struct {
	Video *Video `protobuf:"bytes,16,opt,name=video,proto3,oneof"`
}

type Datapoint_TransformTree struct {
	TransformTree *TransformTree `protobuf:"bytes,18,opt,name=transform_tree,json=transformTree,proto3,oneof"`
}

type Datapoint_Raw struct {
	Raw []byte `protobuf:"bytes,19,opt,name=raw,proto3,oneof"`
}

func (*Datapoint_Text) isDatapoint_Data() {}

func (*Datapoint_Numeric) isDatapoint_Data() {}

func (*Datapoint_NumericSet) isDatapoint_Data() {}

func (*Datapoint_Bitset) isDatapoint_Data() {}

func (*Datapoint_File) isDatapoint_Data() {}

func (*Datapoint_Image) isDatapoint_Data() {}

func (*Datapoint_PointCloud) isDatapoint_Data() {}

func (*Datapoint_Location) isDatapoint_Data() {}

func (*Datapoint_Localization) isDatapoint_Data() {}

func (*Datapoint_Health) isDatapoint_Data() {}

func (*Datapoint_Json) isDatapoint_Data() {}

func (*Datapoint_Battery) isDatapoint_Data() {}

func (*Datapoint_Video) isDatapoint_Data() {}

func (*Datapoint_TransformTree) isDatapoint_Data() {}

func (*Datapoint_Raw) isDatapoint_Data() {}

type AlarmStamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sec           int64                  `protobuf:"varint,1,opt,name=sec,proto3" json:"sec,omitempty"`
	Nanosec       uint32                 `protobuf:"varint,2,opt,name=nanosec,proto3" json:"nanosec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlarmStamp) Reset() {
	*x = AlarmStamp{}
	mi := &file_protos_model_v1_datapoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmStamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmStamp) ProtoMessage() {}

func (x *AlarmStamp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_v1_datapoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmStamp.ProtoReflect.Descriptor instead.
func (*AlarmStamp) Descriptor() ([]byte, []int) {
	return file_protos_model_v1_datapoint_proto_rawDescGZIP(), []int{1}
}

func (x *AlarmStamp) GetSec() int64 {
	if x != nil {
		return x.Sec
	}
	return 0
}

func (x *AlarmStamp) GetNanosec() uint32 {
	if x != nil {
		return x.Nanosec
	}
	return 0
}

type Alarm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Details       string                 `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	Recovery      string                 `protobuf:"bytes,6,opt,name=recovery,proto3" json:"recovery,omitempty"`
	Recoverable   bool                   `protobuf:"varint,7,opt,name=recoverable,proto3" json:"recoverable,omitempty"`
	Image         string                 `protobuf:"bytes,8,opt,name=image,proto3" json:"image,omitempty"`
	StartStamp    *AlarmStamp            `protobuf:"bytes,9,opt,name=start_stamp,json=startStamp,proto3" json:"start_stamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alarm) Reset() {
	*x = Alarm{}
	mi := &file_protos_model_v1_datapoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alarm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alarm) ProtoMessage() {}

func (x *Alarm) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_v1_datapoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alarm.ProtoReflect.Descriptor instead.
func (*Alarm) Descriptor() ([]byte, []int) {
	return file_protos_model_v1_datapoint_proto_rawDescGZIP(), []int{2}
}

func (x *Alarm) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Alarm) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Alarm) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Alarm) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Alarm) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *Alarm) GetRecovery() string {
	if x != nil {
		return x.Recovery
	}
	return ""
}

func (x *Alarm) GetRecoverable() bool {
	if x != nil {
		return x.Recoverable
	}
	return false
}

func (x *Alarm) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Alarm) GetStartStamp() *AlarmStamp {
	if x != nil {
		return x.StartStamp
	}
	return nil
}

// ControlDatapoint contains data sent from Rcc teleop.
type ControlDatapoint struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Stream    string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix epoch time in milliseconds
	Tags      map[string]string      `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Data:
	//
	//	*ControlDatapoint_Text
	//	*ControlDatapoint_Numeric
	//	*ControlDatapoint_Bitset
	//	*ControlDatapoint_Twist
	//	*ControlDatapoint_Pose
	//	*ControlDatapoint_InitialPose
	//	*ControlDatapoint_Point
	//	*ControlDatapoint_GoalId
	Data          isControlDatapoint_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlDatapoint) Reset() {
	*x = ControlDatapoint{}
	mi := &file_protos_model_v1_datapoint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlDatapoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlDatapoint) ProtoMessage() {}

func (x *ControlDatapoint) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_v1_datapoint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlDatapoint.ProtoReflect.Descriptor instead.
func (*ControlDatapoint) Descriptor() ([]byte, []int) {
	return file_protos_model_v1_datapoint_proto_rawDescGZIP(), []int{3}
}

func (x *ControlDatapoint) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *ControlDatapoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ControlDatapoint) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ControlDatapoint) GetData() isControlDatapoint_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ControlDatapoint) GetText() *Text {
	if x != nil {
		if x, ok := x.Data.(*ControlDatapoint_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *ControlDatapoint) GetNumeric() *Numeric {
	if x != nil {
		if x, ok := x.Data.(*ControlDatapoint_Numeric); ok {
			return x.Numeric
		}
	}
	return nil
}

func (x *ControlDatapoint) GetBitset() *Bitset {
	if x != nil {
		if x, ok := x.Data.(*ControlDatapoint_Bitset); ok {
			return x.Bitset
		}
	}
	return nil
}

func (x *ControlDatapoint) GetTwist() *Twist {
	if x != nil {
		if x, ok := x.Data.(*ControlDatapoint_Twist); ok {
			return x.Twist
		}
	}
	return nil
}

func (x *ControlDatapoint) GetPose() []byte {
	if x != nil {
		if x, ok := x.Data.(*ControlDatapoint_Pose); ok {
			return x.Pose
		}
	}
	return nil
}

func (x *ControlDatapoint) GetInitialPose() []byte {
	if x != nil {
		if x, ok := x.Data.(*ControlDatapoint_InitialPose); ok {
			return x.InitialPose
		}
	}
	return nil
}

func (x *ControlDatapoint) GetPoint() *Point {
	if x != nil {
		if x, ok := x.Data.(*ControlDatapoint_Point); ok {
			return x.Point
		}
	}
	return nil
}

func (x *ControlDatapoint) GetGoalId() *GoalID {
	if x != nil {
		if x, ok := x.Data.(*ControlDatapoint_GoalId); ok {
			return x.GoalId
		}
	}
	return nil
}

type isControlDatapoint_Data interface {
	isControlDatapoint_Data()
}

type ControlDatapoint_Text struct {
	Text *Text `protobuf:"bytes,4,opt,name=text,proto3,oneof"`
}

type ControlDatapoint_Numeric struct {
	Numeric *Numeric `protobuf:"bytes,5,opt,name=numeric,proto3,oneof"`
}

type ControlDatapoint_Bitset struct {
	Bitset *Bitset `protobuf:"bytes,6,opt,name=bitset,proto3,oneof"`
}

type ControlDatapoint_Twist struct {
	Twist *Twist `protobuf:"bytes,7,opt,name=twist,proto3,oneof"`
}

type ControlDatapoint_Pose struct {
	Pose []byte `protobuf:"bytes,8,opt,name=pose,proto3,oneof"`
}

type ControlDatapoint_InitialPose struct {
	InitialPose []byte `protobuf:"bytes,9,opt,name=initial_pose,json=initialPose,proto3,oneof"`
}

type ControlDatapoint_Point struct {
	Point *Point `protobuf:"bytes,10,opt,name=point,proto3,oneof"`
}

type ControlDatapoint_GoalId struct {
	GoalId *GoalID `protobuf:"bytes,11,opt,name=goal_id,json=goalId,proto3,oneof"`
}

func (*ControlDatapoint_Text) isControlDatapoint_Data() {}

func (*ControlDatapoint_Numeric) isControlDatapoint_Data() {}

func (*ControlDatapoint_Bitset) isControlDatapoint_Data() {}

func (*ControlDatapoint_Twist) isControlDatapoint_Data() {}

func (*ControlDatapoint_Pose) isControlDatapoint_Data() {}

func (*ControlDatapoint_InitialPose) isControlDatapoint_Data() {}

func (*ControlDatapoint_Point) isControlDatapoint_Data() {}

func (*ControlDatapoint_GoalId) isControlDatapoint_Data() {}

var File_protos_model_v1_datapoint_proto protoreflect.FileDescriptor

const file_protos_model_v1_datapoint_proto_rawDesc = "" +
	"\n" +
	"\x1fprotos/model/v1/datapoint.proto\x12\bv1.model\x1a\x1aprotos/model/v1/file.proto\x1a\x1cprotos/model/v1/health.proto\x1a\x1aprotos/model/v1/math.proto\x1a protos/model/v1/navigation.proto\x1a\x1aprotos/model/v1/text.proto\x1a\x1bprotos/model/v1/media.proto\x1a\x19protos/model/v1/ros.proto\"\x96\a\n" +
	"\tDatapoint\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x121\n" +
	"\x04tags\x18\x03 \x03(\v2\x1d.v1.model.Datapoint.TagsEntryR\x04tags\x12$\n" +
	"\x04text\x18\x04 \x01(\v2\x0e.v1.model.TextH\x00R\x04text\x12-\n" +
	"\anumeric\x18\x05 \x01(\v2\x11.v1.model.NumericH\x00R\anumeric\x127\n" +
	"\vnumeric_set\x18\x11 \x01(\v2\x14.v1.model.NumericSetH\x00R\n" +
	"numericSet\x12*\n" +
	"\x06bitset\x18\a \x01(\v2\x10.v1.model.BitsetH\x00R\x06bitset\x12$\n" +
	"\x04file\x18\b \x01(\v2\x0e.v1.model.FileH\x00R\x04file\x12'\n" +
	"\x05image\x18\t \x01(\v2\x0f.v1.model.ImageH\x00R\x05image\x127\n" +
	"\vpoint_cloud\x18\n" +
	" \x01(\v2\x14.v1.model.PointCloudH\x00R\n" +
	"pointCloud\x120\n" +
	"\blocation\x18\v \x01(\v2\x12.v1.model.LocationH\x00R\blocation\x12<\n" +
	"\flocalization\x18\f \x01(\v2\x16.v1.model.LocalizationH\x00R\flocalization\x12*\n" +
	"\x06health\x18\r \x01(\v2\x10.v1.model.HealthH\x00R\x06health\x12$\n" +
	"\x04json\x18\x0e \x01(\v2\x0e.v1.model.JsonH\x00R\x04json\x12-\n" +
	"\abattery\x18\x0f \x01(\v2\x11.v1.model.BatteryH\x00R\abattery\x12'\n" +
	"\x05video\x18\x10 \x01(\v2\x0f.v1.model.VideoH\x00R\x05video\x12@\n" +
	"\x0etransform_tree\x18\x12 \x01(\v2\x17.v1.model.TransformTreeH\x00R\rtransformTree\x12\x12\n" +
	"\x03raw\x18\x13 \x01(\fH\x00R\x03raw\x12'\n" +
	"\x06alarms\x18\x14 \x03(\v2\x0f.v1.model.AlarmR\x06alarms\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04dataJ\x04\b\x06\x10\a\"8\n" +
	"\n" +
	"AlarmStamp\x12\x10\n" +
	"\x03sec\x18\x01 \x01(\x03R\x03sec\x12\x18\n" +
	"\ananosec\x18\x02 \x01(\rR\ananosec\"\x8c\x02\n" +
	"\x05Alarm\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12\x18\n" +
	"\adetails\x18\x05 \x01(\tR\adetails\x12\x1a\n" +
	"\brecovery\x18\x06 \x01(\tR\brecovery\x12 \n" +
	"\vrecoverable\x18\a \x01(\bR\vrecoverable\x12\x14\n" +
	"\x05image\x18\b \x01(\tR\x05image\x125\n" +
	"\vstart_stamp\x18\t \x01(\v2\x14.v1.model.AlarmStampR\n" +
	"startStamp\"\xfe\x03\n" +
	"\x10ControlDatapoint\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x128\n" +
	"\x04tags\x18\x03 \x03(\v2$.v1.model.ControlDatapoint.TagsEntryR\x04tags\x12$\n" +
	"\x04text\x18\x04 \x01(\v2\x0e.v1.model.TextH\x00R\x04text\x12-\n" +
	"\anumeric\x18\x05 \x01(\v2\x11.v1.model.NumericH\x00R\anumeric\x12*\n" +
	"\x06bitset\x18\x06 \x01(\v2\x10.v1.model.BitsetH\x00R\x06bitset\x12'\n" +
	"\x05twist\x18\a \x01(\v2\x0f.v1.model.TwistH\x00R\x05twist\x12\x14\n" +
	"\x04pose\x18\b \x01(\fH\x00R\x04pose\x12#\n" +
	"\finitial_pose\x18\t \x01(\fH\x00R\vinitialPose\x12'\n" +
	"\x05point\x18\n" +
	" \x01(\v2\x0f.v1.model.PointH\x00R\x05point\x12+\n" +
	"\agoal_id\x18\v \x01(\v2\x10.v1.model.GoalIDH\x00R\x06goalId\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04dataB9Z7github.com/GOAT-Robotics/gtstudio-proto/protos/v1/modelb\x06proto3"

var (
	file_protos_model_v1_datapoint_proto_rawDescOnce sync.Once
	file_protos_model_v1_datapoint_proto_rawDescData []byte
)

func file_protos_model_v1_datapoint_proto_rawDescGZIP() []byte {
	file_protos_model_v1_datapoint_proto_rawDescOnce.Do(func() {
		file_protos_model_v1_datapoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_model_v1_datapoint_proto_rawDesc), len(file_protos_model_v1_datapoint_proto_rawDesc)))
	})
	return file_protos_model_v1_datapoint_proto_rawDescData
}

var file_protos_model_v1_datapoint_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protos_model_v1_datapoint_proto_goTypes = []any{
	(*Datapoint)(nil),        // 0: v1.model.Datapoint
	(*AlarmStamp)(nil),       // 1: v1.model.AlarmStamp
	(*Alarm)(nil),            // 2: v1.model.Alarm
	(*ControlDatapoint)(nil), // 3: v1.model.ControlDatapoint
	nil,                      // 4: v1.model.Datapoint.TagsEntry
	nil,                      // 5: v1.model.ControlDatapoint.TagsEntry
	(*Text)(nil),             // 6: v1.model.Text
	(*Numeric)(nil),          // 7: v1.model.Numeric
	(*NumericSet)(nil),       // 8: v1.model.NumericSet
	(*Bitset)(nil),           // 9: v1.model.Bitset
	(*File)(nil),             // 10: v1.model.File
	(*Image)(nil),            // 11: v1.model.Image
	(*PointCloud)(nil),       // 12: v1.model.PointCloud
	(*Location)(nil),         // 13: v1.model.Location
	(*Localization)(nil),     // 14: v1.model.Localization
	(*Health)(nil),           // 15: v1.model.Health
	(*Json)(nil),             // 16: v1.model.Json
	(*Battery)(nil),          // 17: v1.model.Battery
	(*Video)(nil),            // 18: v1.model.Video
	(*TransformTree)(nil),    // 19: v1.model.TransformTree
	(*Twist)(nil),            // 20: v1.model.Twist
	(*Point)(nil),            // 21: v1.model.Point
	(*GoalID)(nil),           // 22: v1.model.GoalID
}
var file_protos_model_v1_datapoint_proto_depIdxs = []int32{
	4,  // 0: v1.model.Datapoint.tags:type_name -> v1.model.Datapoint.TagsEntry
	6,  // 1: v1.model.Datapoint.text:type_name -> v1.model.Text
	7,  // 2: v1.model.Datapoint.numeric:type_name -> v1.model.Numeric
	8,  // 3: v1.model.Datapoint.numeric_set:type_name -> v1.model.NumericSet
	9,  // 4: v1.model.Datapoint.bitset:type_name -> v1.model.Bitset
	10, // 5: v1.model.Datapoint.file:type_name -> v1.model.File
	11, // 6: v1.model.Datapoint.image:type_name -> v1.model.Image
	12, // 7: v1.model.Datapoint.point_cloud:type_name -> v1.model.PointCloud
	13, // 8: v1.model.Datapoint.location:type_name -> v1.model.Location
	14, // 9: v1.model.Datapoint.localization:type_name -> v1.model.Localization
	15, // 10: v1.model.Datapoint.health:type_name -> v1.model.Health
	16, // 11: v1.model.Datapoint.json:type_name -> v1.model.Json
	17, // 12: v1.model.Datapoint.battery:type_name -> v1.model.Battery
	18, // 13: v1.model.Datapoint.video:type_name -> v1.model.Video
	19, // 14: v1.model.Datapoint.transform_tree:type_name -> v1.model.TransformTree
	2,  // 15: v1.model.Datapoint.alarms:type_name -> v1.model.Alarm
	1,  // 16: v1.model.Alarm.start_stamp:type_name -> v1.model.AlarmStamp
	5,  // 17: v1.model.ControlDatapoint.tags:type_name -> v1.model.ControlDatapoint.TagsEntry
	6,  // 18: v1.model.ControlDatapoint.text:type_name -> v1.model.Text
	7,  // 19: v1.model.ControlDatapoint.numeric:type_name -> v1.model.Numeric
	9,  // 20: v1.model.ControlDatapoint.bitset:type_name -> v1.model.Bitset
	20, // 21: v1.model.ControlDatapoint.twist:type_name -> v1.model.Twist
	21, // 22: v1.model.ControlDatapoint.point:type_name -> v1.model.Point
	22, // 23: v1.model.ControlDatapoint.goal_id:type_name -> v1.model.GoalID
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_protos_model_v1_datapoint_proto_init() }
func file_protos_model_v1_datapoint_proto_init() {
	if File_protos_model_v1_datapoint_proto != nil {
		return
	}
	file_protos_model_v1_file_proto_init()
	file_protos_model_v1_health_proto_init()
	file_protos_model_v1_math_proto_init()
	file_protos_model_v1_navigation_proto_init()
	file_protos_model_v1_text_proto_init()
	file_protos_model_v1_media_proto_init()
	file_protos_model_v1_ros_proto_init()
	file_protos_model_v1_datapoint_proto_msgTypes[0].OneofWrappers = []any{
		(*Datapoint_Text)(nil),
		(*Datapoint_Numeric)(nil),
		(*Datapoint_NumericSet)(nil),
		(*Datapoint_Bitset)(nil),
		(*Datapoint_File)(nil),
		(*Datapoint_Image)(nil),
		(*Datapoint_PointCloud)(nil),
		(*Datapoint_Location)(nil),
		(*Datapoint_Localization)(nil),
		(*Datapoint_Health)(nil),
		(*Datapoint_Json)(nil),
		(*Datapoint_Battery)(nil),
		(*Datapoint_Video)(nil),
		(*Datapoint_TransformTree)(nil),
		(*Datapoint_Raw)(nil),
	}
	file_protos_model_v1_datapoint_proto_msgTypes[3].OneofWrappers = []any{
		(*ControlDatapoint_Text)(nil),
		(*ControlDatapoint_Numeric)(nil),
		(*ControlDatapoint_Bitset)(nil),
		(*ControlDatapoint_Twist)(nil),
		(*ControlDatapoint_Pose)(nil),
		(*ControlDatapoint_InitialPose)(nil),
		(*ControlDatapoint_Point)(nil),
		(*ControlDatapoint_GoalId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_model_v1_datapoint_proto_rawDesc), len(file_protos_model_v1_datapoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_model_v1_datapoint_proto_goTypes,
		DependencyIndexes: file_protos_model_v1_datapoint_proto_depIdxs,
		MessageInfos:      file_protos_model_v1_datapoint_proto_msgTypes,
	}.Build()
	File_protos_model_v1_datapoint_proto = out.File
	file_protos_model_v1_datapoint_proto_goTypes = nil
	file_protos_model_v1_datapoint_proto_depIdxs = nil
}
