// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: protos/model/v1/file.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A File contains either raw bytes of data or an absolute path to a file on the
// local filesystem. Filename is optional and will be auto-generated if it is
// not provided.
type File struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*File_Url
	//	*File_Raw
	Data          isFile_Data `protobuf_oneof:"data"`
	Filename      string      `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"` // auto-generated if not provided, optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_protos_model_v1_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_v1_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_protos_model_v1_file_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetData() isFile_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *File) GetUrl() string {
	if x != nil {
		if x, ok := x.Data.(*File_Url); ok {
			return x.Url
		}
	}
	return ""
}

func (x *File) GetRaw() []byte {
	if x != nil {
		if x, ok := x.Data.(*File_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

func (x *File) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type isFile_Data interface {
	isFile_Data()
}

type File_Url struct {
	// Absolute path to a file on the local filesystem or valid remote URL for
	// remote files
	Url string `protobuf:"bytes,1,opt,name=url,proto3,oneof"`
}

type File_Raw struct {
	// 2MB limit
	Raw []byte `protobuf:"bytes,2,opt,name=raw,proto3,oneof"`
}

func (*File_Url) isFile_Data() {}

func (*File_Raw) isFile_Data() {}

var File_protos_model_v1_file_proto protoreflect.FileDescriptor

const file_protos_model_v1_file_proto_rawDesc = "" +
	"\n" +
	"\x1aprotos/model/v1/file.proto\x12\bv1.model\"X\n" +
	"\x04File\x12\x12\n" +
	"\x03url\x18\x01 \x01(\tH\x00R\x03url\x12\x12\n" +
	"\x03raw\x18\x02 \x01(\fH\x00R\x03raw\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilenameB\x06\n" +
	"\x04dataJ\x04\b\x04\x10\x05B9Z7github.com/GOAT-Robotics/gtstudio-proto/protos/v1/modelb\x06proto3"

var (
	file_protos_model_v1_file_proto_rawDescOnce sync.Once
	file_protos_model_v1_file_proto_rawDescData []byte
)

func file_protos_model_v1_file_proto_rawDescGZIP() []byte {
	file_protos_model_v1_file_proto_rawDescOnce.Do(func() {
		file_protos_model_v1_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_model_v1_file_proto_rawDesc), len(file_protos_model_v1_file_proto_rawDesc)))
	})
	return file_protos_model_v1_file_proto_rawDescData
}

var file_protos_model_v1_file_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_model_v1_file_proto_goTypes = []any{
	(*File)(nil), // 0: v1.model.File
}
var file_protos_model_v1_file_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_model_v1_file_proto_init() }
func file_protos_model_v1_file_proto_init() {
	if File_protos_model_v1_file_proto != nil {
		return
	}
	file_protos_model_v1_file_proto_msgTypes[0].OneofWrappers = []any{
		(*File_Url)(nil),
		(*File_Raw)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_model_v1_file_proto_rawDesc), len(file_protos_model_v1_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_model_v1_file_proto_goTypes,
		DependencyIndexes: file_protos_model_v1_file_proto_depIdxs,
		MessageInfos:      file_protos_model_v1_file_proto_msgTypes,
	}.Build()
	File_protos_model_v1_file_proto = out.File
	file_protos_model_v1_file_proto_goTypes = nil
	file_protos_model_v1_file_proto_depIdxs = nil
}
